using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PBL3.Models // Assuming this is your namespace
{
    public class UserOtp
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string UserId { get; set; } // Foreign Key to AppUser (IdentityUser's Id is string)
        [ForeignKey("UserId")]
        public virtual AppUser User { get; set; } // Navigation property

        [Required]
        [MaxLength(10)]
        public string OtpCode { get; set; } // The 6-digit OTP we send to the user

        [Required]
        public string IdentityPasswordResetToken { get; set; } // The token generated by UserManager

        [Required]
        public DateTime ExpiryTimestampUtc { get; set; }

        public bool IsVerified { get; set; } = false; // To ensure one-time use
    }
}